### PR TITLE
Update functions located in helpers, not wallet

### PR DESCRIPTION
**Pull request by kimdhamilton**
The following functions are located in helpers, not wallet:

- detectPrivateKeyFormat
- privateKeyStringToKey

### CODE REVIEW

**Comment by jtormey** [comment]
Nice find, thanks! Looks like there are two other instances of this issue in rpc-server.js. Do you mind fixing those too before I merge this?

**Comment by kimdhamilton** [comment]
sure, no problem!

**Comment by kimdhamilton** [comment]
Updated -- note the Wallet dependency was no longer needed.

**Comment by jtormey** [comment]
Perfect! Thanks again

**Pull request merged**
